# Generated by Django 2.2.5 on 2019-10-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampleuser',
            options={'verbose_name': '샘플 사용자', 'verbose_name_plural': '샘플 사용자'},
        ),
        migrations.AddField(
            model_name='sampleuser',
            name='useremail',
            field=models.EmailField(default=1, max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
