# Generated by Django 2.2.5 on 2019-11-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleuser', '0002_auto_20191007_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampleuser',
            options={'verbose_name': '테스트 사용자', 'verbose_name_plural': '테스트 사용자'},
        ),
        migrations.AddField(
            model_name='sampleuser',
            name='Best_Place',
            field=models.CharField(default='o', max_length=60, verbose_name='가장 좋았던 곳'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampleuser',
            name='Preferred_Place',
            field=models.CharField(default='o', max_length=60, verbose_name='선호장소'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampleuser',
            name='Preferred_Style',
            field=models.CharField(default='o', max_length=60, verbose_name='여행스타일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampleuser',
            name='Preferred_group',
            field=models.CharField(default='o', max_length=60, verbose_name='동행'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampleuser',
            name='Preferred_term',
            field=models.CharField(default='o', max_length=60, verbose_name='여행기간'),
            preserve_default=False,
        ),
    ]
